### ISSUE TITLE
may be some summary after task execution

### ISSUE THREAD

**Issue by blinov-vitek** [z3d1k/ktlint-maven-plugin#1]
i have big project and too much errors after lint, i want some summary - warnings count, errors count

**Comment by fjfalcon** [comment]
+1, really required.

**Comment by z3d1k** [comment]
There is a little summary information added on the end of lint task in the last version of plugin that shows errors count. Is that what you needed?

**Comment by blinov-vitek** [comment]
may be add something like "in 17 files"?

**Comment by z3d1k** [comment]
done in e514e0e3223cd7f79af4b5a29a0d2ac0784ff64b
